sudo: required

services:
  - docker

before_install:
  - docker build -t shushen/tox .

script:
  - |
      #!/usr/bin/env bash
      set -ex
      readarray -t PYTHON_VERSIONS < PYTHON_VERSIONS
      for v in "${PYTHON_VERSIONS[@]}"; do
        docker run --rm shushen/tox python$v --version
        docker run --rm shushen/tox pip$v --version
        docker run --rm shushen/tox pip$v freeze |grep tox
      done
