sudo: required

services:
  - docker

before_install:
  - docker build -t shushen/tox .

script:
  - docker run --rm shushen/tox python2.7 --version
  - docker run --rm shushen/tox python3.4 --version
  - docker run --rm shushen/tox python3.5 --version
  - docker run --rm shushen/tox python3.6 --version
  - docker run --rm shushen/tox python3.7 --version

  - docker run --rm shushen/tox test -f /root/.pyenv/versions/2.7.15/bin/tox
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.4.9/bin/tox
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.5.6/bin/tox
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.6.6/bin/tox
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.7.0/bin/tox

  - docker run --rm shushen/tox test -f /root/.pyenv/versions/2.7.15/bin/pip
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.4.9/bin/pip
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.5.6/bin/pip
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.6.6/bin/pip
  - docker run --rm shushen/tox test -f /root/.pyenv/versions/3.7.0/bin/pip
